version: '3'

services:

  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"

  web:
    build:
      context: .
    ports: 
      - "8080:8080"
    links:
      - db
    depends_on:
      - db