version: '3'

services:

  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"

  web:
    command: "/go/bin/bee run -downdoc=true -gendoc=true"
    working_dir: "/go/src/github.com/gnosis/pm-kyc-service"
    build:
      context: .
    ports: 
      - "8080:8080"
    links:
      - db
    depends_on:
      - db